# Generated by Django 4.2.2 on 2023-07-26 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0005_producttags_productdetails_productabout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_lond_description',
            new_name='product_long_description',
        ),
    ]
