# Generated by Django 4.2.2 on 2023-07-27 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0006_rename_product_lond_description_products_product_long_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_long_description',
        ),
    ]
